INSERT INTO category(description) VALUES ('AMERICAN');
INSERT INTO category(description) VALUES ('INDIAN');
INSERT INTO category(description) VALUES ('ITALIAN');
INSERT INTO category(description) VALUES ('MEXICAN');
INSERT INTO unit_of_measure(description) VALUES ('Teaspoon');
INSERT INTO unit_of_measure(description) VALUES ('Tablespoon');
INSERT INTO unit_of_measure(description) VALUES ('Cup');
INSERT INTO unit_of_measure(description) VALUES ('Pinch');
INSERT INTO unit_of_measure(description) VALUES ('Ounce');